package espn

import (
	"time"

	"nfl-quiniela-2026/db"
)

// OfficialWeek3PowerRankings holds the verified ESPN NFL Power Rankings after Week 3 2026
var OfficialWeek3PowerRankings = []*db.TeamPowerRanking{
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "KC",
		Rank:         1,
		PreviousRank: 4,
		RankChange:   3,
		Record:       "3-0",
		Analysis:     "¿Volvieron los Chiefs? Volvieron los Chiefs. Un 3-0 bien ganado, con un Patrick Mahomes (¡y Travis Kelce!) renovado. Ante Las Vegas, tendrán un duelo ante los Raiders significativo por primera vez en temporadas. Aún así, parten como favoritos frente a sus viejos rivales.",
		Author:       "Eric Gómez",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "SF",
		Rank:         2,
		PreviousRank: 3,
		RankChange:   1,
		Record:       "3-0",
		Analysis:     "Tantas lesiones y se las arreglaron para seguir invictos en la campaña. Kyle Shanahan demostró que tiene un libro de opciones y que van a pelear la cima de la NFC Oeste.",
		Author:       "Fernando Villa",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "BUF",
		Rank:         3,
		PreviousRank: 2,
		RankChange:   -1,
		Record:       "3-0",
		Analysis:     "Qué importante es ganar hasta jugando mal. ¿Habrá sido este el peor partido de la temporada regular de Josh Allen y Buffalo?",
		Author:       "Víctor Manuel Macín",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "DEN",
		Rank:         4,
		PreviousRank: 9,
		RankChange:   5,
		Record:       "2-1",
		Analysis:     "Vencieron a los Rams en uno de los juegos nocturnos más entretenidos del año --ojalá y se puedan reencontrar más adelante--. De destacarse el hecho que anotaron sus 30 puntos en prácticamente un cuarto y medio.",
		Author:       "Luis Miguel Vasavilbaso",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "BAL",
		Rank:         5,
		PreviousRank: 12,
		RankChange:   7,
		Record:       "2-1",
		Analysis:     "No hay forma más futbolera de salir del Maracaná que en hombros después de meter el gol (de campo) de la victoria en el último segundo, un día que jamás olvidará Tyler Loop.",
		Author:       "Erick Cervantes Roon",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "CHI",
		Rank:         6,
		PreviousRank: 19,
		RankChange:   13,
		Record:       "2-1",
		Analysis:     "La habilidad y talento de Caleb Williams la potencian, pero la victoria sobre los Eagles con el veterano QB Case Keenum al mando es testimonio de que el sistema ofensivo de los Bears es la clave de su reciente éxito.",
		Author:       "Ivis Aburto",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "MIN",
		Rank:         7,
		PreviousRank: 10,
		RankChange:   3,
		Record:       "3-0",
		Analysis:     "Los próximos cuatro rivales en el calendario son: Dolphins, Saints, Colts y Lions. Así, la probabilidad de que lleguen 7-0 a su duelo contra los Bills no luce taaaaan descabellada.",
		Author:       "Alfonso Mancilla",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "JAX",
		Rank:         8,
		PreviousRank: 17,
		RankChange:   9,
		Record:       "2-1",
		Analysis:     "Auténtico dominio de unos Jaguars que brillaron frente a unos desconocidos Patriots. Trevor Lawrence ha demostrado que puede ser el quarterback y el líder que Jacksonville necesita para trascender en los playoffs. Los Jaguars están encaminados a ganar la AFC Sur.",
		Author:       "Jorge Garrett",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "SEA",
		Rank:         9,
		PreviousRank: 1,
		RankChange:   -8,
		Record:       "2-1",
		Analysis:     "Un descalabro inesperado contra los Commanders es lo necesario para despertar a los campeones antes de su enfrentamiento frente a los Chargers, quienes buscan sumar su primera victoria en una temporada de terror.",
		Author:       "Eric Gómez",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "DET",
		Rank:         10,
		PreviousRank: 16,
		RankChange:   6,
		Record:       "2-1",
		Analysis:     "Tuvieron un partido más complicado de lo previsto, pero Jahmyr Gibbs fue la salvación en el ataque terrestre y gracias a él consiguieron la victoria.",
		Author:       "Fernando Villa",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "LV",
		Rank:         11,
		PreviousRank: 14,
		RankChange:   3,
		Record:       "3-0",
		Analysis:     "Nadie, absolutamente nadie, veía un 3-0 de Raiders. Pero siguen los Chiefs y las apuestas en Las Vegas deben pagar muy bien la victoria local.",
		Author:       "Víctor Manuel Macín",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "PIT",
		Rank:         12,
		PreviousRank: 22,
		RankChange:   10,
		Record:       "2-1",
		Analysis:     "Su victoria permitió que todos los equipos de la AFC Norte ostenten marca de 2-1 y también lavó un poco la imagen que habían dejado una semana atrás en Foxboro.",
		Author:       "Luis Miguel Vasavilbaso",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "LAR",
		Rank:         13,
		PreviousRank: 6,
		RankChange:   -7,
		Record:       "1-2",
		Analysis:     "Con 1-2, los Rams están coqueteando peligrosamente con la etiqueta de mayor decepción de la temporada.",
		Author:       "Erick Cervantes Roon",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "PHI",
		Rank:         14,
		PreviousRank: 7,
		RankChange:   -7,
		Record:       "2-1",
		Analysis:     "El potencial está allí, pero la ejecución y mala toma de decisiones desde la banca no ayudan a alcanzarlo. Jalen Hurts no lo puede hacer todo.",
		Author:       "Ivis Aburto",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "CIN",
		Rank:         15,
		PreviousRank: 5,
		RankChange:   -10,
		Record:       "1-2",
		Analysis:     "La derrota frente a Steelers les dará la dosis de realidad que el equipo necesitaba. Siguen perdiendo los duelos importantes.",
		Author:       "Alfonso Mancilla",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "DAL",
		Rank:         16,
		PreviousRank: 11,
		RankChange:   -5,
		Record:       "1-2",
		Analysis:     "Llevamos tres partidos de la temporada y los Cowboys no encuentran el rumbo. El apuntado debe ser George Pickens, quien tuvo una muy destacada pretemporada, pero que simplemente no encuentra el nivel. Ya son cinco partidos sin anotación para él. Hora de despertar para la ofensiva de Dallas.",
		Author:       "Jorge Garrett",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "NYG",
		Rank:         17,
		PreviousRank: 25,
		RankChange:   8,
		Record:       "1-2",
		Analysis:     "Luego de perder a Jaxson Dart, comenzó el show de Jameis Winston, quien los guió a una victoria. ¿La mala noticia? El rival fueron los Titans, un equipo bastante pobre. Esta semana, la dificultad no subirá mucho ante los Arizona Cardinals.",
		Author:       "Eric Gómez",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "IND",
		Rank:         18,
		PreviousRank: 21,
		RankChange:   3,
		Record:       "1-2",
		Analysis:     "Demostraron que tener un buen pateador es clave y Spencer Shrader tuvo nueve de los 19 puntos del equipo. Mucho por mejorar en el equipo de Shane Steichen, pero al menos ya ganaron.",
		Author:       "Fernando Villa",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "WSH",
		Rank:         19,
		PreviousRank: 28,
		RankChange:   9,
		Record:       "2-1",
		Analysis:     "Sam Darnold completó 31 de 45 pases para 379 yardas y 4 TD. No es que los Seahawks jugaran mal, pero la ofensiva encabezada por Marcus Mariota no paró de contestar los puntos rivales y la defensiva se encargó de interceptar dos veces al QB campeón de la NFL; una de esas jugadas grandes selló la sorpresiva victoria.",
		Author:       "Víctor Manuel Macín",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "CLE",
		Rank:         20,
		PreviousRank: 20,
		RankChange:   0,
		Record:       "1-2",
		Analysis:     "Su debut en casa estuvo acompañado de una victoria importante ante los Panthers detrás de una defensiva de respeto, pero ahora veremos si mantienen el paso cuando abran su calendario divisional ante los Steelers.",
		Author:       "Luis Miguel Vasavilbaso",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "ATL",
		Rank:         21,
		PreviousRank: 32,
		RankChange:   11,
		Record:       "1-2",
		Analysis:     "Los Falcons llegaron como víctimas a Lambeau Field, pero Bijan Robinson tenía otros planes y demostró por qué es el mejor corredor de la NFL en la actualidad.",
		Author:       "Erick Cervantes Roon",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "NE",
		Rank:         22,
		PreviousRank: 8,
		RankChange:   -14,
		Record:       "1-2",
		Analysis:     "Drake Maye se ve como un QB con clara desconfianza en sí mismo y que necesita un abrazo de su coach y coordinador ofensivo que le ayude a recuperar confianza.",
		Author:       "Ivis Aburto",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "CAR",
		Rank:         23,
		PreviousRank: 15,
		RankChange:   -8,
		Record:       "1-2",
		Analysis:     "La buena, siguen como líderes divisionales. La mala: lideran la peor división de la NFL. La peor: los equipos comenzarán a castigar más duro a Bryce Young.",
		Author:       "Alfonso Mancilla",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "NO",
		Rank:         24,
		PreviousRank: 18,
		RankChange:   -6,
		Record:       "1-2",
		Analysis:     "No sé si alguien tenía grandes expectativas de los Saints antes de la temporada. Al menos yo no. En todo caso, han sido un equipo batallador. Casi dan la sorpresa frente a Lions, vencieron a Ravens y se quedaron cerca del triunfo ante Raiders. Pulgar arriba para los Saints en estas primeras semanas.",
		Author:       "Jorge Garrett",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "GB",
		Rank:         25,
		PreviousRank: 13,
		RankChange:   -12,
		Record:       "1-2",
		Analysis:     "De no ser por los Jets, Green Bay estaría 0-3, algo impensable al inicio de la temporada. Hay algo seriamente mal con la defensiva del equipo, sin Micah Parsons, y la ofensiva tampoco ha sido de lo más brillante. Los Buccaneers, rival de la Semana 4, están aún peor. ¿Quién sale avante?.",
		Author:       "Eric Gómez",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "HOU",
		Rank:         26,
		PreviousRank: 23,
		RankChange:   -3,
		Record:       "0-3",
		Analysis:     "DeMeco Ryans no encuentra las respuestas para darle a C.J. Stroud una mejor ofensiva y más opciones para anotar. No parece que vayan a levantar pronto el paso.",
		Author:       "Fernando Villa",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "NYJ",
		Rank:         27,
		PreviousRank: 26,
		RankChange:   -1,
		Record:       "1-2",
		Analysis:     "Buen juego de New York en Detroit: Geno Smith, 31/37, 321 yardas, 3TD ¡0 intercepciones! El cuerpo de receptores dio un partidazo con grandes recepciones, pero la defensiva no pudo contener a Goff y Gibbs y ahí perdieron el juego. Pero si Geno entrega consistentemente actuaciones como esta, los Jets van a superar expectativas.",
		Author:       "Víctor Manuel Macín",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "ARI",
		Rank:         28,
		PreviousRank: 27,
		RankChange:   -1,
		Record:       "1-2",
		Analysis:     "La defensiva volvió a permitir más de 30 puntos y eso muy pocas veces se traducirá en triunfos, pero hay que rescatar la reacción que tuvieron ante los 49ers, contrario a lo que ocurrió una semana atrás contra los Seahawks.",
		Author:       "Luis Miguel Vasavilbaso",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "TB",
		Rank:         29,
		PreviousRank: 24,
		RankChange:   -5,
		Record:       "1-2",
		Analysis:     "Su temporada ya iba camino al abismo con Baker Mayfield sano, ahora que tendrán que jugar sin él las próximas tres semanas no se sorprendan si los vemos convertidos en un equipo 0-6.",
		Author:       "Erick Cervantes Roon",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "LAC",
		Rank:         30,
		PreviousRank: 30,
		RankChange:   0,
		Record:       "0-3",
		Analysis:     "Con récord de 0-3, los Chargers sí compiten por algo, con los Buccaneers por la etiqueta de la mayor decepción de la temporada 2026.",
		Author:       "Ivis Aburto",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "TEN",
		Rank:         31,
		PreviousRank: 29,
		RankChange:   -2,
		Record:       "0-3",
		Analysis:     "Es uno de los equipos que luce como sólido contendiente… a obtener el pick N° 1 Draft 2027.",
		Author:       "Alfonso Mancilla",
		UpdatedAt:    time.Now(),
	},
	{
		SeasonYear:   2026,
		WeekNumber:   3,
		TeamCode:     "MIA",
		Rank:         32,
		PreviousRank: 31,
		RankChange:   -1,
		Record:       "0-3",
		Analysis:     "Los Dolphins simplemente no saben nadar. Son por mucho el peor equipo de la NFL; no se les ve un norte. Sí, perdieron contra uno de los tres mejores equipos en la Semana 3, pero no hay un rumbo prometedor para Miami. Será un largo año para los Fins.",
		Author:       "Jorge Garrett",
		UpdatedAt:    time.Now(),
	},
}

// FetchPowerRankings returns the weekly ESPN Power Rankings, with 100% offline fallback
func (c *Client) FetchPowerRankings(seasonYear, weekNumber int, teamMap map[string]*db.Team) ([]*db.TeamPowerRanking, error) {
	// For Season 2026 Week 3 (or latest default), return official rankings enriched with team metadata
	rankings := make([]*db.TeamPowerRanking, 0, len(OfficialWeek3PowerRankings))
	for _, orig := range OfficialWeek3PowerRankings {
		pr := *orig
		if t, ok := teamMap[pr.TeamCode]; ok {
			pr.TeamID = t.ID
			pr.TeamName = t.Name
			pr.TeamCity = t.City
			pr.LogoURL = t.LogoURL
			pr.PrimaryColor = t.PrimaryColor
			pr.Conference = t.Conference
			pr.Division = t.Division
		}
		rankings = append(rankings, &pr)
	}
	return rankings, nil
}
